- hosts: nginxrun
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
---
- hosts: nginx
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
---
  - hosts: docker
    become: true
    tasks:
    - name: install docker
      apt:
      pkg:
      - apt-get install 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common
      state: latest
      update_cache: true
      
    - name: add GPG KEY
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: add repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
        
    - name: install docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli 
        - containerd.io
        state: latest
        update_cache: true
        
      
        

